version: '3'

services:
  php:
    container_name: pwr-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - pwr-network

  nginx:
    container_name: pwr-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pwr-network

  node:
    container_name: pwr-node
    build:
      context: ./docker/node
      dockerfile: Dockerfile.node
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - pwr-network

  mysql:
    container_name: pwr-mysql
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - pwr-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - pwr-network
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    container_name: pwr-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - pwr-network
    environment:
      PMA_HOST: pwr-mysql
    depends_on:
      - mysql

  redis:
    container_name: pwr-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'

networks:
  pwr-network:
    driver: bridge

volumes:
  pwr-data:
    driver: local
